function createSearchPreset(
  id,
  name,
  { includedTypes = [], includedPrimaryTypes = [] },
) {
  return Object.freeze({
    id,
    name,
    includedTypes: Object.freeze([...includedTypes]),
    includedPrimaryTypes: Object.freeze([...includedPrimaryTypes]),
  });
}

export const DEFAULT_RESTAURANT_SEARCH_PRESET_ID = "all";

// Broad restaurant matching covers cuisine subtypes while keeping Everything
// within Google's 50-primary-type request limit. Preset overlap is intentional.
export const RESTAURANT_SEARCH_PRESETS = Object.freeze([
  createSearchPreset("all", "Everything", {
    includedPrimaryTypes: [
      "restaurant",
      "cafe",
      "coffee_shop",
      "coffee_stand",
      "coffee_roastery",
      "tea_house",
      "cat_cafe",
      "dog_cafe",
      "bakery",
      "bagel_shop",
      "donut_shop",
      "deli",
      "food_court",
      "meal_takeaway",
      "meal_delivery",
      "pizza_delivery",
      "acai_shop",
      "cake_shop",
      "candy_store",
      "chocolate_shop",
      "chocolate_factory",
      "confectionery",
      "dessert_shop",
      "ice_cream_shop",
      "juice_shop",
      "pastry_shop",
      "salad_shop",
      "sandwich_shop",
      "snack_bar",
      "hot_dog_stand",
      "kebab_shop",
      "bar",
      "bar_and_grill",
      "beer_garden",
      "brewery",
      "brewpub",
      "cocktail_bar",
      "gastropub",
      "hookah_bar",
      "irish_pub",
      "lounge_bar",
      "pub",
      "sports_bar",
      "wine_bar",
      "winery",
      "cafeteria",
      "breakfast_restaurant",
      "brunch_restaurant",
      "noodle_shop",
    ],
  }),
  createSearchPreset("coffee-brunch", "Coffee & Breakfast", {
    includedPrimaryTypes: [
      "coffee_shop",
      "coffee_stand",
      "coffee_roastery",
      "cafe",
      "cat_cafe",
      "dog_cafe",
      "tea_house",
      "breakfast_restaurant",
      "brunch_restaurant",
      "bagel_shop",
      "bakery",
      "donut_shop",
      "diner",
    ],
  }),
  createSearchPreset("american-casual", "American & Comfort Food", {
    includedPrimaryTypes: [
      "american_restaurant",
      "barbecue_restaurant",
      "hamburger_restaurant",
      "steak_house",
      "diner",
      "soul_food_restaurant",
      "cajun_restaurant",
      "californian_restaurant",
      "southwestern_us_restaurant",
      "hawaiian_restaurant",
      "chicken_restaurant",
      "chicken_wings_restaurant",
      "hot_dog_restaurant",
      "hot_dog_stand",
      "bar_and_grill",
      "gastropub",
    ],
  }),
  createSearchPreset("asian", "East & Southeast Asian", {
    includedPrimaryTypes: [
      "asian_restaurant",
      "asian_fusion_restaurant",
      "burmese_restaurant",
      "cambodian_restaurant",
      "cantonese_restaurant",
      "chinese_restaurant",
      "chinese_noodle_restaurant",
      "dim_sum_restaurant",
      "dumpling_restaurant",
      "filipino_restaurant",
      "hot_pot_restaurant",
      "indonesian_restaurant",
      "japanese_restaurant",
      "japanese_curry_restaurant",
      "japanese_izakaya_restaurant",
      "korean_restaurant",
      "korean_barbecue_restaurant",
      "malaysian_restaurant",
      "mongolian_barbecue_restaurant",
      "noodle_shop",
      "ramen_restaurant",
      "sushi_restaurant",
      "taiwanese_restaurant",
      "thai_restaurant",
      "tibetan_restaurant",
      "tonkatsu_restaurant",
      "vietnamese_restaurant",
      "yakiniku_restaurant",
      "yakitori_restaurant",
    ],
  }),
  createSearchPreset("south-asian", "Indian & South Asian", {
    includedPrimaryTypes: [
      "indian_restaurant",
      "north_indian_restaurant",
      "south_indian_restaurant",
      "pakistani_restaurant",
      "bangladeshi_restaurant",
      "sri_lankan_restaurant",
      "afghani_restaurant",
    ],
  }),
  createSearchPreset("latin-caribbean", "Latin & Caribbean", {
    includedPrimaryTypes: [
      "latin_american_restaurant",
      "south_american_restaurant",
      "argentinian_restaurant",
      "brazilian_restaurant",
      "burrito_restaurant",
      "caribbean_restaurant",
      "chilean_restaurant",
      "colombian_restaurant",
      "cuban_restaurant",
      "mexican_restaurant",
      "peruvian_restaurant",
      "taco_restaurant",
      "tex_mex_restaurant",
    ],
  }),
  createSearchPreset("italian", "Italian", {
    includedPrimaryTypes: ["italian_restaurant"],
  }),
  createSearchPreset("european", "European", {
    includedPrimaryTypes: [
      "european_restaurant",
      "austrian_restaurant",
      "basque_restaurant",
      "bavarian_restaurant",
      "belgian_restaurant",
      "bistro",
      "british_restaurant",
      "croatian_restaurant",
      "czech_restaurant",
      "danish_restaurant",
      "dutch_restaurant",
      "eastern_european_restaurant",
      "fish_and_chips_restaurant",
      "fondue_restaurant",
      "french_restaurant",
      "german_restaurant",
      "greek_restaurant",
      "hungarian_restaurant",
      "irish_restaurant",
      "italian_restaurant",
      "polish_restaurant",
      "portuguese_restaurant",
      "romanian_restaurant",
      "russian_restaurant",
      "scandinavian_restaurant",
      "spanish_restaurant",
      "swiss_restaurant",
      "tapas_restaurant",
      "ukrainian_restaurant",
    ],
  }),
  createSearchPreset("mediterranean-middle-eastern", "Mediterranean & Middle Eastern", {
    includedPrimaryTypes: [
      "mediterranean_restaurant",
      "middle_eastern_restaurant",
      "falafel_restaurant",
      "greek_restaurant",
      "gyro_restaurant",
      "israeli_restaurant",
      "kebab_shop",
      "lebanese_restaurant",
      "moroccan_restaurant",
      "persian_restaurant",
      "shawarma_restaurant",
      "turkish_restaurant",
    ],
  }),
  createSearchPreset("african", "African", {
    includedPrimaryTypes: [
      "african_restaurant",
      "ethiopian_restaurant",
      "moroccan_restaurant",
    ],
  }),
  createSearchPreset("pizza-sandwiches", "Pizza & Sandwiches", {
    includedPrimaryTypes: [
      "pizza_restaurant",
      "pizza_delivery",
      "sandwich_shop",
      "deli",
      "bagel_shop",
    ],
  }),
  createSearchPreset("seafood", "Seafood", {
    includedPrimaryTypes: [
      "seafood_restaurant",
      "oyster_bar_restaurant",
      "fish_and_chips_restaurant",
      "sushi_restaurant",
    ],
  }),
  createSearchPreset("bars-pubs", "Bars & Pubs", {
    includedPrimaryTypes: [
      "bar",
      "bar_and_grill",
      "beer_garden",
      "brewery",
      "brewpub",
      "cocktail_bar",
      "gastropub",
      "hookah_bar",
      "irish_pub",
      "lounge_bar",
      "pub",
      "sports_bar",
      "wine_bar",
      "winery",
    ],
  }),
  createSearchPreset("vegetarian-light", "Vegetarian & Lighter Meals", {
    includedPrimaryTypes: [
      "vegan_restaurant",
      "vegetarian_restaurant",
      "salad_shop",
      "soup_restaurant",
      "juice_shop",
      "acai_shop",
    ],
  }),
]);

const SEARCH_PRESETS_BY_ID = new Map(
  RESTAURANT_SEARCH_PRESETS.map((preset) => [preset.id, preset]),
);

export function getRestaurantSearchPreset(id) {
  return SEARCH_PRESETS_BY_ID.get(id);
}
